# Generated by Django 5.1.5 on 2025-12-31 19:17

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='resume',
            field=models.FileField(storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='resumes/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='file',
            field=models.FileField(storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='resumes/%Y/%m/'),
        ),
    ]
